app-id: com.tekkengreg.bigbrowser.runtime
runtime: org.gnome.Platform
runtime-version: '48'
sdk: org.gnome.Sdk//48
command: tauri-runtime

finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --socket=fallback-x11
  - --share=network
  - --device=dri
  - --socket=pulseaudio
  - --socket=session-bus
  - --talk-name=org.freedesktop.Flatpak
  - --system-talk-name=org.freedesktop.NetworkManager
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.freedesktop.portal.*
  - --talk-name=org.a11y.Bus
  - --filesystem=xdg-download:rw
  - --filesystem=xdg-documents:rw
  - --filesystem=xdg-pictures:rw
  - --filesystem=xdg-videos:rw
  - --env=GTK_USE_PORTAL=1
  - --env=WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1
  - --env=WEBKIT_DISABLE_COMPOSITING_MODE=1
  - --env=WEBKIT_DISABLE_DMABUF_RENDERER=1
  - --env=WEBKIT_FORCE_SANDBOX=0
  - --env=XDG_CURRENT_DESKTOP=GNOME

modules:
  - name: tauri-runtime
    buildsystem: simple
    build-commands:
      - echo "Installing Tauri Runtime"
      - mkdir -p /app/bin /app/share/applications /app/share/icons/hicolor/128x128/apps /app/share/metainfo
      - install -Dm755 runtime /app/bin/tauri-runtime
      - install -Dm644 com.tekkengreg.bigbrowser.runtime.png /app/share/icons/hicolor/128x128/apps/com.tekkengreg.bigbrowser.runtime.png
      - |
        cat > /app/share/applications/com.tekkengreg.bigbrowser.runtime.desktop << 'EOF'
        [Desktop Entry]
        Name=BigBrowser Runtime (Tauri)
        Comment=Modern web browser runtime built with Tauri and Rust
        Exec=tauri-runtime %U
        Icon=com.tekkengreg.bigbrowser.runtime
        Terminal=false
        Type=Application
        StartupWMClass=BigBrowser
        Categories=Network;WebBrowser;
        Keywords=browser;web;internet;tauri;runtime;
        StartupNotify=true
        MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
        EOF
      - |
        cat > /app/share/metainfo/com.tekkengreg.bigbrowser.runtime.metainfo.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <component type="desktop-application">
          <id>com.tekkengreg.bigbrowser.runtime</id>
          <metadata_license>CC-BY-SA-4.0</metadata_license>
          <project_license>MIT</project_license>
          <name>BigBrowser Runtime (Tauri)</name>
          <summary>Modern web browser runtime built with Tauri and Rust</summary>
          <description>
            <p>BigBrowser Runtime is a modern web browser runtime application built with Tauri and Rust. It provides a secure, fast, and lightweight browsing experience with native performance.</p>
            <p>Features:</p>
            <ul>
              <li>Built with Tauri for native performance</li>
              <li>Secure sandboxed browsing environment</li>
              <li>Low memory footprint</li>
              <li>Cross-platform compatibility</li>
              <li>Modern web standards support</li>
            </ul>
          </description>
          <categories>
            <category>Network</category>
            <category>WebBrowser</category>
          </categories>
          <keywords>
            <keyword>browser</keyword>
            <keyword>web</keyword>
            <keyword>internet</keyword>
            <keyword>tauri</keyword>
            <keyword>runtime</keyword>
          </keywords>
          <url type="homepage">https://github.com/tekkengreg/big-browser</url>
          <launchable type="desktop-id">com.tekkengreg.bigbrowser.runtime.desktop</launchable>
          <provides>
            <binary>tauri-runtime</binary>
          </provides>
        </component>
        EOF
    sources:
      - type: file
        path: ../apps/runtime/src-tauri/target/release/runtime
      - type: file
        path: ../icons/bigbrowser.png
        dest-filename: com.tekkengreg.bigbrowser.runtime.png 